// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD67Yx7BP0sWdt-BNVzP4hYYpfWXTJttA',
    appId: '1:839629473384:web:fd2ae88045b06c70bcdddd',
    messagingSenderId: '839629473384',
    projectId: 'genzlib-2',
    authDomain: 'genzlib-2.firebaseapp.com',
    storageBucket: 'genzlib-2.firebasestorage.app',
    measurementId: 'G-70GS17VM33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjOfGAckVLokwssAqZHPMbszJ6hdTRKYQ',
    appId: '1:839629473384:android:54f6236cf8eb7585bcdddd',
    messagingSenderId: '839629473384',
    projectId: 'genzlib-2',
    storageBucket: 'genzlib-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzzSnstSOzHBTRQg3VkeGYuZ3LmyDGmlg',
    appId: '1:839629473384:ios:7ad0b8eed4bf4edcbcdddd',
    messagingSenderId: '839629473384',
    projectId: 'genzlib-2',
    storageBucket: 'genzlib-2.firebasestorage.app',
    iosBundleId: 'com.example.lib1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzzSnstSOzHBTRQg3VkeGYuZ3LmyDGmlg',
    appId: '1:839629473384:ios:7ad0b8eed4bf4edcbcdddd',
    messagingSenderId: '839629473384',
    projectId: 'genzlib-2',
    storageBucket: 'genzlib-2.firebasestorage.app',
    iosBundleId: 'com.example.lib1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD67Yx7BP0sWdt-BNVzP4hYYpfWXTJttA',
    appId: '1:839629473384:web:1b0900a342490cb0bcdddd',
    messagingSenderId: '839629473384',
    projectId: 'genzlib-2',
    authDomain: 'genzlib-2.firebaseapp.com',
    storageBucket: 'genzlib-2.firebasestorage.app',
    measurementId: 'G-5CFK88DG2D',
  );
}
